[project]
name = "wit"
version = "0.0.1"

[tool.pytest.ini_options]
pythonpath = [
  ".", "src",
]

# [tool.setuptools]
# package-dir = {"" = "wit"}
#
# [tool.setuptools.packages.find]
# where = ["wit"]
